SKILL_DIR="${AGENT_WORKSPACE}/skills/${SKILL_DIR_NAME}"
AGENTS_FILE="${AGENT_WORKSPACE}/AGENTS.md"
SOUL_FILE="${AGENT_WORKSPACE}/SOUL.md"
IDENTITY_FILE="${AGENT_WORKSPACE}/IDENTITY.md"
TASK_CLI_PATH="${SKILL_DIR}/task-cli.py"
SKILL_MD_PATH="${SKILL_DIR}/SKILL.md"

mkdir -p "${AGENT_WORKSPACE}"
mkdir -p "${SKILL_DIR}"
